# top level stuff you probably don't need to touch
highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 8000
safe: true
# baseurl: https://takehiromouri.github.io/


# edit here to achieve your personal greatness
url: http://www.takehiromouri.com
title: Takehiro Mouri
author: Takehiro Mouri
description: Ruby on Rails developer. I'm passionate about writing and teaching code.
avatar: prof.jpg
email: takehiromouri@gmail.com
github: takehiromouri
twitter: takehiromouri
linkedin: takehiro-mouri-a3083487
stackoverflow: takehiro-mouri   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus 
google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
